-- schema.sql for Consignment Tracker

CREATE TABLE IF NOT EXISTS shipment (
    id SERIAL PRIMARY KEY,
    tracking VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(100),
    origin_lat DOUBLE PRECISION NOT NULL,
    origin_lng DOUBLE PRECISION NOT NULL,
    dest_lat DOUBLE PRECISION NOT NULL,
    dest_lng DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) DEFAULT 'Created',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS checkpoint (
    id SERIAL PRIMARY KEY,
    shipment_id INTEGER NOT NULL REFERENCES shipment(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    label VARCHAR(50) NOT NULL,
    note TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriber (
    id SERIAL PRIMARY KEY,
    shipment_id INTEGER NOT NULL REFERENCES shipment(id) ON DELETE CASCADE,
    email VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);
